ALTER TABLE COURSE_TEACHER DROP CONSTRAINT IF EXISTS fk_courseteacher_teacher;
ALTER TABLE COURSE_TEACHER
    ADD CONSTRAINT fk_courseteacher_teacher FOREIGN KEY (teacher_id) REFERENCES TEACHER (user_id) ON DELETE CASCADE;

ALTER TABLE GRADE DROP CONSTRAINT IF EXISTS fk_grade_student;
ALTER TABLE GRADE
    ADD CONSTRAINT fk_grade_student FOREIGN KEY (student_id) REFERENCES STUDENT (user_id) ON DELETE CASCADE;

ALTER TABLE STUDENT_GROUP_HISTORY DROP CONSTRAINT IF EXISTS fk_sgh_student;
ALTER TABLE STUDENT_GROUP_HISTORY
    ADD CONSTRAINT fk_sgh_student FOREIGN KEY (student_id) REFERENCES STUDENT (user_id) ON DELETE CASCADE;