ALTER TABLE ADMIN DROP CONSTRAINT IF EXISTS fk_admin_user;
ALTER TABLE TEACHER DROP CONSTRAINT IF EXISTS fk_teacher_user;
ALTER TABLE STUDENT DROP CONSTRAINT IF EXISTS fk_student_user;
ALTER TABLE GRADE_HISTORY DROP CONSTRAINT IF EXISTS fk_gradehistory_user;

DROP TABLE IF EXISTS "USER" CASCADE;

CREATE TABLE "user" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    role VARCHAR(50) NOT NULL,
    address TEXT,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    entrance_date_time TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'STUDENT', 'TEACHER'))
);

ALTER TABLE ADMIN
    ADD CONSTRAINT fk_admin_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE TEACHER
    ADD CONSTRAINT fk_teacher_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE STUDENT
    ADD CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE GRADE_HISTORY
    ADD CONSTRAINT fk_gradehistory_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;